### ISSUE TITLE
quizの見た目をかっこよくしたい

### ISSUE THREAD

**Issue by momo-0315** [posse-ap/posse2-hackathon-202202-team2C#30]
## 確認事項

* ラベルつけてね
* assignしてね。自分自身か他の誰か

## やってほしいこと
質問文はネオンにできたら（あんまり激しくなりすぎないように）
選択肢を画像にすると画像が多すぎるかもと思った（選択肢を画像にするなら質問文は文字だけとか）
clearした後の色変更ももうちょいサイトにあった感じにしたい

## まだやらなくていいこと
* 別のissue作るなりしてください。作ったらいい感じに連携させておいてね。

**Comment by reitanoue** [comment]
下にミニゲームページに飛べるようなアンカータグを張る
